name: Deploy to Cloud Foundry

on:
  push:
    branches:
    - dev-scp

jobs:
  build:
    runs-on: ubuntu-18.04
    # Build your app here

  deploy:
    runs-on: ubuntu-18.04
    needs: build
    
    steps:
    - uses: dg4101/covid19@dev-scp
      with:
        cf_api: https://api.cf.eu10.hana.ondemand.com
        cf_username: ${{ secrets.CF_USER }}
        cf_password: ${{ secrets.CF_PASSWORD }}
        cf_org: i030702trial
        cf_space: dev
        command: cf push stopcovid19 -c "yarn dev"
