name: Deploy to Cloud Foundry

on:
  push:
    branches:
    - dev-scp

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: CF Push1
      uses: dg4101/cf-cli@master
      with:
        cf_api: https://api.cf.eu10.hana.ondemand.com
        cf_username: ${{ secrets.CF_USER }}
        cf_password: ${{ secrets.CF_PASSWORD }}
        cf_org: i030702trial
        cf_space: dev
        command: push stopcovid19 -f manifest.yaml -p covid19 -c "yarn dev"
