name: Deploy to Cloud Foundry

on:
  push:
    branches:
    - dev-scp

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: dg4101/covid19@dev-scp

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
          
    - name: CF Push
      uses: dg4101/covid19@dev-scp
      with:
        cf_api: https://api.cf.eu10.hana.ondemand.com
        cf_username: ${{ secrets.CF_USER }}
        cf_password: ${{ secrets.CF_PASSWORD }}
        cf_org: i030702trial
        cf_space: dev
        command: cf push stopcovid19 -c "yarn dev"
