name: Deploy to Cloud Foundry

on:
  push:
    branches:
    - dev-scp

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: govau/cf-cli
      with:
        cf_api: https://api.cf.eu10.hana.ondemand.com
        cf_username: ${{ secrets.CF_USER }}
        cf_password: ${{ secrets.CF_PASSWORD }}
        cf_org: i030702trial
        cf_space: dev
    - run: pwd
    - run: git clone https://github.com/dg4101/covid19.git
    - run: git checkout dev-scp
    - run: echo ====================;pwd;find .

    - run: cf api "$INPUT_CF_API";cf auth "$INPUT_CF_USERNAME" "$INPUT_CF_PASSWORD"
    - run: cf target -o "$INPUT_CF_ORG" -s "$INPUT_CF_SPACE"
    - run: cf push stopcovid19 -f ./cf/manifest.yaml -c "yarn dev"

