name: Deploy to Cloud Foundry

on:
  push:
    branches:
    - dev-scp

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: govau/cf-cli
    - name: Setup repo
      run: pwd

    - run: git clone https://github.com/dg4101/covid19.git
    - run: git checkout dev-scp
    - run: echo ====================;pwd;find .

    - run: cf api https://api.cf.eu10.hana.ondemand.com;cf auth ${{ secrets.CF_USER }} ${{ secrets.CF_PASSWORD }}
    - run: cf target -o i030702trial -s dev
    - run: cf push stopcovid19 -f ./cf/manifest.yaml -c "yarn dev"

