name: Deploy to Cloud Foundry

on:
  push:
    branches:
    - dev-scp

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        ref: dev-scp
      # Runs a single command using the runners shell
    - name: Test env
      run: echo Hello, world!;pwd;find .
    - name: Setup cf-cli
      run: apt-get update;apt-get install -y ca-certificates jq;echo "deb [trusted=yes] https://packages.cloudfoundry.org/debian stable main" > /etc/apt/sources.list.d/cloudfoundry-cli.list;apt-get update;apt-get install -y cf-cli
    - name: Test cli
      run: cf --version      
